# HW2: Encrypt and Decrypt
#
# In this exercise, we will write functions to encrypt and decrypt strings that only consist of lower-case characters.
#
# 1. Use `seq_along` function to map the characters to their positions i.e. a -> 1, b -> 2, ..., z -> 26.
#    Store the result into tibble `t1` with 2 columns: character and position. Each row contains a character and its position.
#    Hint: You may use `letters` to obtain a vector of 26 characters.
# 2. Use tibble `t1` to assign to `n1` the position of character `"n"`. Note: `n1` should be an integer instead of a list.
# 3. Write a function `move(char,nstep=5)` that return the character that is `nstep` steps after the input character `char`.
#    Note: When the position is larger than 26, start from the beginning i.e. 1.
#    Example : both `move("a",nstep=1)` and `move("z",nstep=2)` should return character `"b"`.
# 4. Use `strsplit` function to split the string "statistics" into characters and then apply the `move` function to move each element in the string by 5 steps using `sapply`. The result should be stored into a vector `v1`.
# 5. Write a function `encrypt(str,nstep)`. This function returns a string that each element is moved _nstep_ steps by using `move` function.
# 6. Write a function `decrypt(str,nstep)` to decrypt the string generated by `encrypt` function.
library(tibble)
## Do not modify this line! ## Write your code for 1. after this line! ##
a <-c(letters)
b <-seq_along(a)
t1 <-tibble(character=a,position=b)
## Do not modify this line! ## Write your code for 2. after this line! ##
n1 <-t1$position[t1$character=="n"]
## Do not modify this line! ## Write your code for 3. after this line! ##
move <- function(char,nstep=5){
  if(t1$position[t1$character ==char]+nstep>26){
    step <- (t1$position[t1$character ==char]+nstep)%%26
  }
  else{step <-t1$position[t1$character ==char]+nstep}
  if((t1$position[t1$character ==char]+nstep)%%26 ==0){step <-26}
  result <-t1$character[t1$position==step]
  return(result)
}
c <-move("u",31)
## Do not modify this line! ## Write your code for 4. after this line! ##
s1 <-strsplit("statistics",NULL)
s1 <-unlist(s1)
v1 <-sapply(s1,move)
## Do not modify this line! ## Write your code for 5. after this line! ##
encrypt <-function(str,nstep){
  str1 <-strsplit(str,NULL)
  str1 <-unlist(str1)
  result1 <-sapply(str1, function(x){move(x,nstep)})
  result <-paste(result1,sep = "",collapse = "")
  return(result)
}
h <-encrypt("abcdf",1)

## Do not modify this line! ## Write your code for 6. after this line! ##
decrypt<-function(str,nstep){
  if(nstep%%26==0&nstep>=26){return(str)}
  else if(nstep<26){return(encrypt(str,26-nstep))}
  else {return(encrypt(str,(26-nstep%%26)))}
}

